apiVersion: argoproj.io/v1alpha1 # ArgoCD Application resource
kind: Application               # Kind of resource
metadata:                        # Metadata section                         
  name: nginx-frontend          # App name
  namespace: argocd             # Must exist in ArgoCD namespace
spec:
  project: default        # Assigns app to the frontend-team Project
  source:
    repoURL: https://github.com/ashekhawat-cd/argo-prac.git   # Git repo
    targetRevision: main        # Branch to watch
    path: 04_first_app_deployment/ui_approach/nginx     # Path in repo with manifests
  destination:
    server: https://trainaks-training-1ac2ca-b61zelaq.hcp.canadacentral.azmk8s.io:443  # Target cluster, run `argocd cluster list` to see
    namespace: frontend          # Namespace inside that cluster
  syncPolicy:                    # Sync policy settings
    automated:                   # Enable automated sync
      prune: true                 # Delete resources removed from Git
      selfHeal: true              # Correct drift if resources change in cluster
    syncOptions:                 # Additional sync options
      - CreateNamespace=true      # Auto-create namespace if it doesn't exist